name: dartlery
dependencies:
  browser: any
  crypto: any
  image: any
  json_schema_output:
    path: ../dart_json_schema_output/
  logging: any
  mime: any
  mongo_dart: any
  polymer: any
  rest_client:
    path: ../rest_client
  rest_server:
    path: ../rest_server/
  sqljocky: any
transformers:
- polymer:
    entry_points: web/dartlery.html
