name: dartlery
dependencies:
  browser: any
  crypto: any
  image:
  logging: any
  mime: any
  mongo_dart: any
  polymer: any
  rest_server:
    path: ../rest_server/
  sqljocky: any
transformers:
- polymer:
    entry_points: web/dartlery.html