name: dartlery_server
description: A sample command-line application
dependencies:
  crypto: any
  image:
    path: ../image
  logging: any
  mime: any
  mongo_dart: any
  path: any
  rest_dart:
    path: ../rest_dart
  sqljocky: any
