name: dartlery
description: Angular web client for the dartlery application
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  dartlery_shared:
    path: ../shared
  api_client:
    path: ../api_client

  angular: ^4.0.0
  angular_components: ^0.7.0
  angular_router: ^1.0.2
  angular_forms: ^1.0.0


  logging_handlers: ^0.8.0
  option: ^1.2.0
  _discoveryapis_commons: ^0.1.3
  mime: ^0.9.3

  angular_image_compare:
    path: ../../angular_image_compare
    #git: https://github.com/dartninja/angular_image_compare.git

  lib_angular:
    path: ../libs/angular
  tools:
    path: ../libs/tools
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions:
    - --enable-experimental-mirrors