name: dartlery
description: Angular web client for the dartlery application
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  dartlery_shared:
    path: ../shared
  api_client:
    path: ../api_client

  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  angular_router: any
  angular_forms: any


  logging_handlers: ^0.8.0
  option: ^1.2.0
  _discoveryapis_commons: ^0.1.3
  mime: 0.9.5

  angular_image_compare:
    path: ../../angular_image_compare
    #git: https://github.com/dartninja/angular_image_compare.git

dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  angular_compiler: any
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
