name: dartlery
version: 0.1.0
description: Media collection management application
author: Matthew Barbour <sanmadjack@gmail.com>
homepage: https://github.com/dartlery

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  dartlery_shared:
    path: ../shared
  dice: "^1.8.0"
  args: any
  connection_pool: ^0.1.2
  crypt: ^1.0.2
  http_server: ^0.9.6
  image: ^2.0.3
  logging_handlers: ^0.8.0
  meta: ^1.0.5
<<<<<<< HEAD
  mongo_dart: ^0.3.1
=======
  mongo_dart: ^0.2.10
  postgres: any
>>>>>>> master
  option: ^1.2.0
  options_file: ^0.11.0
  rpc: ^0.5.9
  shelf: ^0.6.5
  shelf_auth: ^0.7.3
  shelf_exception_handler: ^0.1.0
  shelf_route: ^0.14.3
  shelf_rpc: ^0.0.3
  shelf_static: ^0.2.5
  plugin: ^0.2.0
#  version: any
  sqljocky:
    git: https://github.com/dart-drivers/mysql.git
  mime: 0.9.5
  hex: ^0.1.1
  exif:
    git: https://github.com/dartninja/dartexif.git
  image_hash:
    git:
      url: https://github.com/dartninja/image_hash.git
      ref: 16b4f42633d08760d65c8034b6fdf31e27cee9a4

dev_dependencies:
  build_runner: ^0.8.7
  build_test: ^0.10.0
  test: any
dependency_overrides:
<<<<<<< HEAD
=======
#  image:
#    git: https://github.com/brendan-duncan/image.git
#  rpc:
#    git: git://github.com/dart-lang/rpc.git
>>>>>>> master
#  image_hash:
#    path: ../../image_hash/
#  dart_jwt: "^0.6.0"
#  fixnum: ^0.10.0
executables:
  dartalog-server: server
